version: '3.8'

services:
  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...'
        sleep 30
        kafka-topics --create --topic telemetry.sensors.v1
                     --partitions 1 --replication-factor 1 --if-not-exists
                     --bootstrap-server kafka:29092 &&
        kafka-topics --create --topic telemetry.snapshots.v1
                     --partitions 1 --replication-factor 1 --if-not-exists
                     --bootstrap-server kafka:29092 &&
        kafka-topics --create --topic telemetry.hubs.v1
                     --partitions 1 --replication-factor 1 --if-not-exists
                     --bootstrap-server kafka:29092
      "

  postgres:
    image: postgres:15
    container_name: smart_home_postgres
    environment:
      POSTGRES_DB: smart_home
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  store-db:
    image: postgres:16.1
    container_name: store-db
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store
    ports:
      - "5433:5432"
    volumes:
      - store_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U store -d store"]
      interval: 10s
      timeout: 5s
      retries: 5

  cart-db:
    image: postgres:16.1
    container_name: cart-db
    environment:
      POSTGRES_DB: cart
      POSTGRES_USER: cart
      POSTGRES_PASSWORD: cart
    ports:
      - "5434:5432"
    volumes:
      - cart_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cart -d cart"]
      interval: 10s
      timeout: 5s
      retries: 5

  warehouse-db:
    image: postgres:16.1
    container_name: warehouse-db
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
    ports:
      - "5435:5432"
    volumes:
      - warehouse_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warehouse -d warehouse"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-db:
    image: postgres:16.1
    container_name: order-db
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
    ports:
      - "5436:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U warehouse -d warehouse" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-db:
    image: postgres:16.1
    container_name: payment-db
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
    ports:
      - "5437:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U warehouse -d warehouse" ]
      interval: 10s
      timeout: 5s
      retries: 5

  delivery-db:
    image: postgres:16.1
    container_name: delivery-db
    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: delivery
    ports:
      - "5438:5432"
    volumes:
      - delivery_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U warehouse -d warehouse" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  store_data:
  cart_data:
  warehouse_data:
  order_data:
  payment_data:
  delivery_data: