spring:
  application:
    name: analyzer
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888
      retry:
        initial-interval: 2000
        max-interval: 6000
        max-attempts: 10