server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: analyzer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analyzer-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      max-poll-records: 50
    listener:
      missing-topics-fatal: false
      ack-mode: manual
    properties:
      max.poll.interval.ms: 300000
      session.timeout.ms: 10000

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart_home
    username: postgres
    password: 12345

app:
  kafka:
    topics:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1
      snapshots: telemetry.snapshots.v1

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum.telemetry.analyzer: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: DEBUG
    org.hibernate.SQL: DEBUG